hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpanel")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprctl setcursor Adwaita 24")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("QT_SCALE_FACTOR=1 qs")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("env QT_NO_XDG_DESKTOP_PORTAL=1 /usr/lib/kdeconnectd")
    hl.exec_cmd("env QT_NO_XDG_DESKTOP_PORTAL=1 kdeconnect-indicator")
    hl.exec_cmd("~/.local/bin/notification-logger.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal")
    hl.exec_cmd("hyprctl plugin load /run/current-system/sw/lib/hyprglass.so")
    -- hl.exec_cmd("hyprpm reload -n")
end)
