require("userconfigs.monitors")
require("userconfigs.auto_exec")
-- require("userconfigs.default_programs")
require("userconfigs.env_var")
require("userconfigs.permissions")
require("userconfigs.look")
require("userconfigs.animations")
require("userconfigs.windowrules")
require("userconfigs.layout")
require("userconfigs.input")
require("userconfigs.keybinds")
require("userconfigs.plugins")
