# Auto-generated by nixos-hardware-detect
# This file contains machine-specific hardware profile settings.
{ ... }:

{
  hardwareProfile = {
    gpu = {
      type = "nvidia-hybrid-amd";
      open = true;
      nvidiaDriver = "stable";
      prime = {
        amdgpuBusId = "PCI:6:0:0";
        nvidiaBusId = "PCI:1:0:0";
      };
    };
    laptop = {
      enable = true;
      lenovoLegion = true;
      realtekWifiFix = true;
    };
  };
}
