# Files and directories
music_directory     "/home/alastair_oberon/Music"
playlist_directory  "/home/alastair_oberon/.config/mpd/playlists"
db_file             "/home/alastair_oberon/.config/mpd/database"
log_file            "/home/alastair_oberon/.config/mpd/log"
pid_file            "/home/alastair_oberon/.config/mpd/pid"
state_file          "/home/alastair_oberon/.config/mpd/state"
sticker_file        "/home/alastair_oberon/.config/mpd/sticker.sql"

# Network
bind_to_address     "127.0.0.1"
port                "6600"
restore_paused      "yes"
auto_update         "yes"

# Audio Output (PipeWire)
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}

# Visualizer (For ncmpcpp)
audio_output {
    type                    "fifo"
    name                    "Visualizer Feed"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
